"""Add reminder field to ToDo model

Revision ID: 3d03198589ef
Revises: b7e09676b52a
Create Date: 2024-06-11 09:07:29.099014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d03198589ef'
down_revision = 'b7e09676b52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder', sa.Boolean(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=140),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=280),
               existing_nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               nullable=True,
               existing_server_default=sa.text("'low'"))
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('to_do', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'low'"))
        batch_op.alter_column('description',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=140),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('reminder')

    # ### end Alembic commands ###
